import { useMemo, useState } from 'react';

const PROVIDERS = {
  huawei: '华为云 DNS', aliyun: '阿里云 DNS', tencent: '腾讯云 DNSPod API', dnspod: 'DNSPod 独立 API', cloudflare: 'Cloudflare',
  godaddy: 'GoDaddy', porkbun: 'Porkbun', cloudns: 'ClouDNS', callback: '自定义 HTTPS 回调',
  aliyun_esa: '阿里云 ESA', baidu: '百度云', namecheap: 'Namecheap', namesilo: 'NameSilo', dynadot: 'Dynadot',
  dnsla: 'DNSLA', era: '时代互联 / Eranet', tndns: 'Tnethk', gcore: 'Gcore', edgeone: '腾讯 EdgeOne',
  ns1: 'IBM NS1 Connect', rainyun: '雨云', dynv6: 'Dynv6', vercel: 'Vercel DNS', spaceship: 'Spaceship'
};
const STATUS = { online: '在线', pending: '待接入', revoked: '已吊销', healthy: '正常', down: '故障', observing: '观察中', unknown: '未检测', queued: '等待执行', pending_approval: '待确认', allocating: '分配 IP', automating: '执行任务', dns_updating: '更新 DNS', verifying: '验证中', succeeded: '已完成', failed: '失败', rolled_back: '已回滚', active: '使用中', locked: '已锁定', released: '已释放' };

const EMPTY = {
  probe: { name: '', region: '', carrier: '', maxConcurrency: 100, enabled: true },
  target: { name: '', address: '', allowPrivate: false, checkType: 'tcp', port: 443, interval: 30, timeout: 5, failureThreshold: 3, recoveryThreshold: 2, quorumMode: 'majority', quorumCount: 2, probeIds: [], policyId: '', enabled: true },
  asset: { name: '', address: '', region: '', carrier: '', labels: '', health: 'unknown', enabled: true, note: '' },
  pool: { name: '', assetIds: [], allocationMode: 'one', allocationCount: 1, selectionMode: 'ordered', sharingMode: 'exclusive', shareLimit: 1, leaseMinutes: 30, cooldownMinutes: 10, enabled: true, note: '' },
  account: { name: '', provider: 'huawei', region: 'cn-north-4', projectId: '', zoneAllowlist: '', enabled: true, credentials: {} },
  zone: { name: '', accountId: '', providerZoneId: '', enabled: true },
  binding: { name: '', zoneId: '', accountId: '', domain: '', recordName: '@', recordType: 'A', providerRecordId: '', recordLine: '默认', ttl: 60, updateMode: 'managed_replace', ddnsSources: [], backupIps: '', maxActiveIps: 50, pruneStale: true, healthEnabled: true, healthInterval: 30, maxParallel: 20, enabled: true },
  policy: { name: '', poolIds: [], automationTaskId: '', automationHosts: 'allocated', automationTimeout: 1800, dnsBindingIds: [], approvalMode: 'automatic', autoRollback: true, enabled: true, businessKey: '' }
  ,bot: { name: '', token: '', enabled: true, userIds: '', groupIds: '', rolesText: '', menuScopes: ['overview', 'probes', 'incidents', 'pools', 'dns', 'automation'] }
};

export default function OrchestrationWorkspace({ tab, state, api, onState, toast, Dialog }) {
  const [section, setSection] = useState(tab === 'probes' ? 'nodes' : tab === 'pools' ? 'assets' : 'accounts');
  const [editor, setEditor] = useState({ open: false, type: '', value: null });
  const [install, setInstall] = useState(null);
  const sections = tab === 'probes'
    ? [['nodes', '探针节点'], ['targets', '检查目标'], ['policies', '切换策略'], ['incidents', '故障事件'], ['bots', 'Telegram']]
    : tab === 'pools'
      ? [['assets', 'IP 资产'], ['pools', '备用池'], ['leases', '当前租约']]
      : [['accounts', '服务商账号'], ['zones', 'DNS Zone'], ['bindings', '解析绑定'], ['changes', '变更记录']];
  const active = sections.some(([key]) => key === section) ? section : sections[0][0];

  const openCreate = (type) => setEditor({ open: true, type, value: structuredClone(EMPTY[type]) });
  const openEdit = (type, value) => setEditor({ open: true, type, value: normalizeDraft(type, value) });
  const closeEditor = () => setEditor({ open: false, type: '', value: null });
  const save = async () => {
    try {
      const resource = resourceFor(editor.type);
      const value = serializeDraft(editor.type, editor.value);
      const data = await api(`/api/orchestration/${resource}${value.id ? `/${value.id}` : ''}`, { method: value.id ? 'PUT' : 'POST', body: JSON.stringify(value) });
      onState(data.state);
      closeEditor();
      toast('已保存');
    } catch (error) { toast(error.message); }
  };
  const remove = async () => {
    try {
      const data = await api(`/api/orchestration/${resourceFor(editor.type)}/${editor.value.id}`, { method: 'DELETE' });
      onState(data.state);
      closeEditor();
      toast('已删除');
    } catch (error) { toast(error.message); }
  };
  const rotateProbe = async (id) => {
    try {
      const data = await api(`/api/probes/${id}/rotate-token`, { method: 'POST' });
      onState(data.state);
      setInstall(data);
    } catch (error) { toast(error.message); }
  };
  const executeIncident = async (id) => {
    try {
      const data = await api(`/api/incidents/${id}/execute`, { method: 'POST' });
      onState(data.state);
      toast('故障编排已启动');
    } catch (error) { toast(error.message); }
  };
  const rollbackIncident = async (id) => {
    try {
      const data = await api(`/api/incidents/${id}/rollback`, { method: 'POST' });
      onState(data.state);
      toast('已执行回滚');
    } catch (error) { toast(error.message); }
  };

  return (
    <section className="ops-workspace">
      <header className="surface ops-header">
        <div><span className="ops-eyebrow">{tab === 'probes' ? '可用性与故障编排' : tab === 'pools' ? '地址资源与并发租约' : '多云 DNS 控制平面'}</span><strong>{tab === 'probes' ? '探针管理' : tab === 'pools' ? '备用 IP 池' : '解析管理'}</strong></div>
        <div className="ops-health"><i /><span>{summary(tab, state)}</span></div>
      </header>
      <div className="ops-tabs" role="tablist">{sections.map(([key, label]) => <button key={key} className={active === key ? 'active' : ''} onClick={() => setSection(key)}>{label}<em>{countFor(key, state)}</em></button>)}</div>
      <div className="surface ops-content">
        {renderSection(active, { state, openCreate, openEdit, rotateProbe, executeIncident, rollbackIncident, api, onState, toast })}
      </div>

      {editor.open ? <Dialog title={`${editor.value.id ? '编辑' : '新增'}${typeLabel(editor.type)}`} className="ops-editor-dialog" wide={editor.type !== 'target' && editor.type !== 'policy'} xwide={editor.type === 'target' || editor.type === 'policy'} onClose={closeEditor} footer={<><div>{editor.value.id ? <button className="danger-text" onClick={remove}>删除</button> : null}</div><div className="dialog-actions"><button className="ghost" onClick={closeEditor}>取消</button><button className="primary" onClick={save}>保存</button></div></>}>{renderEditor(editor.type, editor.value, (patch) => setEditor((current) => ({ ...current, value: { ...current.value, ...patch } })), state)}</Dialog> : null}
      {install ? <Dialog title="探针接入" onClose={() => setInstall(null)} footer={<><span /><button className="primary" onClick={() => setInstall(null)}>完成</button></>}><div className="ops-install"><label>安装命令</label><pre>{install.installCommand}</pre><label>一次性注册令牌</label><pre>{install.token}</pre><label>卸载命令</label><pre>{install.uninstallCommand}</pre><span>执行安装命令后，在隐藏输入处粘贴令牌。令牌 15 分钟内有效且仅能使用一次。</span></div></Dialog> : null}
    </section>
  );
}

function renderSection(section, ctx) {
  const { state } = ctx;
  if (section === 'nodes') return <DataView title="探针节点" copy="一台探针可承载多个检查目标" action="新增探针" onAction={() => ctx.openCreate('probe')} empty="还没有探针节点">{state.probes?.map((item) => <Row key={item.id} title={item.name} subtitle={`${item.region || '未设置地区'} · ${item.carrier || '未设置线路'} · ${item.agentVersion || '未接入'}`} status={STATUS[item.status] || item.status} tone={item.status === 'online' ? 'ok' : 'muted'} actions={<><button className="ghost" onClick={() => ctx.rotateProbe(item.id)}>接入命令</button><button className="ghost" onClick={() => ctx.openEdit('probe', item)}>编辑</button></>} />)}</DataView>;
  if (section === 'targets') return <DataView title="检查目标" copy="支持 Ping、TCP 和多探针仲裁" action="新增目标" onAction={() => ctx.openCreate('target')} empty="还没有检查目标">{state.probeTargets?.map((item) => <Row key={item.id} title={item.name} subtitle={`${item.checkType === 'ping' ? 'PING' : `TCP:${item.port}`} · ${item.address} · ${item.probeIds?.length || 0} 个探针`} status={STATUS[item.health] || item.health} tone={item.health === 'healthy' ? 'ok' : item.health === 'down' ? 'bad' : 'warn'} actions={<button className="ghost" onClick={() => ctx.openEdit('target', item)}>编辑</button>} />)}</DataView>;
  if (section === 'policies') return <DataView title="切换策略" copy="把检查目标、备用池、自动化和 DNS 串成一条可回滚流程" action="新增策略" onAction={() => ctx.openCreate('policy')} empty="还没有切换策略">{state.failoverPolicies?.map((item) => <Row key={item.id} title={item.name} subtitle={`${item.poolIds?.length || 0} 个池 · ${item.dnsBindingIds?.length || 0} 条解析 · ${item.approvalMode === 'telegram' ? '需确认' : '自动执行'}`} status={item.enabled ? '已启用' : '已停用'} tone={item.enabled ? 'ok' : 'muted'} actions={<button className="ghost" onClick={() => ctx.openEdit('policy', item)}>编辑</button>} />)}</DataView>;
  if (section === 'incidents') return <DataView title="故障事件" copy="每个目标只允许一个活动事件，失败可按快照回滚" empty="还没有故障事件">{state.incidents?.map((item) => <Row key={item.id} title={item.targetName} subtitle={`${formatTime(item.startedAt)} · ${item.message || item.error || item.policyName}`} status={STATUS[item.status] || item.status} tone={item.status === 'succeeded' ? 'ok' : item.status === 'failed' ? 'bad' : 'warn'} actions={<>{['pending_approval', 'failed', 'observing'].includes(item.status) ? <button className="primary" onClick={() => ctx.executeIncident(item.id)}>执行</button> : null}{item.dnsChangeIds?.length && item.status !== 'rolled_back' ? <button className="ghost" onClick={() => ctx.rollbackIncident(item.id)}>回滚</button> : null}</>} />)}</DataView>;
  if (section === 'bots') return <DataView title="Telegram 机器人" copy="多个 Bot 可分别授权用户、群组和菜单范围" action="新增机器人" onAction={() => ctx.openCreate('bot')} empty="还没有 Telegram 机器人">{state.telegramBots?.map((item) => <Row key={item.id} title={item.name} subtitle={`${item.userIds?.length || 0} 个用户 · ${item.groupIds?.length || 0} 个群组 · ${item.menuScopes?.length || 0} 个菜单`} status={item.enabled && item.configured ? '运行中' : item.configured ? '已停用' : '未配置 Token'} tone={item.enabled && item.configured ? 'ok' : 'muted'} actions={<button className="ghost" onClick={() => ctx.openEdit('bot', item)}>编辑</button>} />)}</DataView>;
  if (section === 'assets') return <DataView title="IP 资产" copy="一个 IP 可加入多个备用池并服务多个业务" action="新增 IP" onAction={() => ctx.openCreate('asset')} empty="还没有 IP 资产">{state.ipAssets?.map((item) => <Row key={item.id} title={item.name || item.address} subtitle={`${item.address} · ${item.region || '未设置地区'} · ${item.carrier || '未设置线路'}`} status={STATUS[item.health] || item.health} tone={item.health === 'healthy' ? 'ok' : item.health === 'unhealthy' ? 'bad' : 'muted'} actions={<button className="ghost" onClick={() => ctx.openEdit('asset', item)}>编辑</button>} />)}</DataView>;
  if (section === 'pools') return <DataView title="备用池" copy="支持单个、指定数量、全部取用和多种共享策略" action="新增备用池" onAction={() => ctx.openCreate('pool')} empty="还没有备用池">{state.ipPools?.map((item) => <Row key={item.id} title={item.name} subtitle={`${item.assetIds?.length || 0} 个 IP · ${allocationLabel(item)} · ${sharingLabel(item.sharingMode)}`} status={item.enabled ? '可分配' : '已停用'} tone={item.enabled ? 'ok' : 'muted'} actions={<button className="ghost" onClick={() => ctx.openEdit('pool', item)}>编辑</button>} />)}</DataView>;
  if (section === 'leases') return <DataView title="IP 租约" copy="共享容量与独占锁均由服务端事务校验" empty="还没有租约记录">{state.ipLeases?.map((item) => { const asset = state.ipAssets?.find((entry) => entry.id === item.assetId); const pool = state.ipPools?.find((entry) => entry.id === item.poolId); return <Row key={item.id} title={asset?.address || item.assetId} subtitle={`${pool?.name || '未知池'} · 到期 ${formatTime(item.expiresAt)}`} status={STATUS[item.status] || item.status} tone={item.status === 'active' ? 'ok' : item.status === 'released' ? 'muted' : 'warn'} actions={['active', 'locked'].includes(item.status) ? <button className="ghost" onClick={async () => { const data = await ctx.api(`/api/ip-leases/${item.id}/release`, { method: 'POST' }); ctx.onState(data.state); ctx.toast('租约已释放'); }}>释放</button> : null} />; })}</DataView>;
  if (section === 'accounts') return <DataView title="服务商账号" copy="支持多个服务商、同服务商多个账号和 Zone 白名单" action="新增账号" onAction={() => ctx.openCreate('account')} empty="还没有 DNS 服务商账号">{state.dnsAccounts?.map((item) => <Row key={item.id} title={item.name} subtitle={`${PROVIDERS[item.provider] || item.provider} · ${item.zoneAllowlist?.length || 0} 个授权 Zone`} status={item.configured ? (item.status === 'healthy' ? '连接正常' : '待测试') : '未配置凭证'} tone={item.status === 'healthy' ? 'ok' : 'warn'} actions={<><button className="ghost" onClick={async () => { try { await ctx.api(`/api/dns-accounts/${item.id}/test`, { method: 'POST' }); ctx.toast('连接测试成功'); } catch (error) { ctx.toast(error.message); } }}>测试</button><button className="ghost" onClick={() => ctx.openEdit('account', item)}>编辑</button></>} />)}</DataView>;
  if (section === 'zones') return <DataView title="DNS Zone" copy="一个权威 Zone 只绑定一个主写入账号" action="新增 Zone" onAction={() => ctx.openCreate('zone')} empty="还没有 DNS Zone">{state.dnsZones?.map((item) => <Row key={item.id} title={item.name} subtitle={`${state.dnsAccounts?.find((entry) => entry.id === item.accountId)?.name || '未关联账号'} · ${item.providerZoneId || '未填写 Zone ID'}`} status={item.enabled ? '已托管' : '已停用'} tone={item.enabled ? 'ok' : 'muted'} actions={<button className="ghost" onClick={() => ctx.openEdit('zone', item)}>编辑</button>} />)}</DataView>;
  if (section === 'bindings') return <DataView title="解析绑定" copy="支持多来源解析、备用域名、备用 IP、A/AAAA、健康检测和失效清理" action="新增解析绑定" onAction={() => ctx.openCreate('binding')} empty="还没有解析绑定">{state.dnsBindings?.map((item) => <Row key={item.id} title={item.name} subtitle={`${item.recordType} · ${item.domain} · ${item.ddnsSources?.length || 0} 个来源 · ${item.backupIps?.length || 0} 个备用 IP`} status={item.enabled ? '已启用' : '已停用'} tone={item.enabled ? 'ok' : 'muted'} actions={<><button className="ghost" onClick={async () => { try { const data = await ctx.api(`/api/dns-bindings/${item.id}/sync`, { method: 'POST' }); ctx.onState(data.state); ctx.toast('解析已同步'); } catch (error) { ctx.toast(error.message); } }}>立即同步</button><button className="ghost" onClick={() => ctx.openEdit('binding', item)}>编辑</button></>} />)}</DataView>;
  return <DataView title="DNS 变更" copy="保留变更前后快照，可从故障事件执行整组回滚" empty="还没有 DNS 变更记录">{state.dnsChanges?.map((item) => <Row key={item.id} title={item.domain} subtitle={`${item.beforeValues?.join(', ') || '空'} → ${item.afterValues?.join(', ') || '空'} · ${formatTime(item.createdAt)}`} status={item.status === 'rolled_back' ? '已回滚' : '已应用'} tone={item.status === 'rolled_back' ? 'muted' : 'ok'} />)}</DataView>;
}

function DataView({ title, copy, action, onAction, empty, children }) {
  const items = Array.isArray(children) ? children.filter(Boolean) : children ? [children] : [];
  return <><div className="ops-content-head"><div><strong>{title}</strong><span>{copy}</span></div>{action ? <button className="primary" onClick={onAction}>{action}</button> : null}</div><div className="ops-list">{items.length ? items : <div className="ops-empty"><strong>{empty}</strong><span>使用右上角操作开始配置。</span></div>}</div></>;
}

function Row({ title, subtitle, status, tone = 'muted', actions }) {
  return <article className="ops-row"><div className="ops-row-main"><span className={`ops-dot ${tone}`} /><div><strong>{title}</strong><span>{subtitle}</span></div></div><div className="ops-row-side"><em className={`ops-status ${tone}`}>{status}</em>{actions ? <div className="ops-row-actions">{actions}</div> : null}</div></article>;
}

function renderEditor(type, value, patch, state) {
  if (type === 'probe') return <EditorGrid><Field label="探针名称"><input value={value.name} onChange={(e) => patch({ name: e.target.value })} /></Field><Field label="地区"><input value={value.region} onChange={(e) => patch({ region: e.target.value })} placeholder="例如：上海" /></Field><Field label="运营商/线路"><input value={value.carrier} onChange={(e) => patch({ carrier: e.target.value })} placeholder="例如：电信" /></Field><Field label="最大检查并发"><input type="number" min="1" max="1000" value={value.maxConcurrency} onChange={(e) => patch({ maxConcurrency: e.target.value })} /></Field><Toggle checked={value.enabled} onChange={(enabled) => patch({ enabled })}>启用探针</Toggle></EditorGrid>;
  if (type === 'target') return <EditorGrid><Field label="目标名称"><input value={value.name} onChange={(e) => patch({ name: e.target.value })} /></Field><Field label="地址"><input value={value.address} onChange={(e) => patch({ address: e.target.value })} placeholder="IP 或域名" /></Field><Field label="检查类型"><select value={value.checkType} onChange={(e) => patch({ checkType: e.target.value })}><option value="tcp">TCP</option><option value="ping">Ping</option></select></Field><Field label="TCP 端口"><input type="number" disabled={value.checkType === 'ping'} value={value.port} onChange={(e) => patch({ port: e.target.value })} /></Field><Field label="检查间隔（秒）"><input type="number" value={value.interval} onChange={(e) => patch({ interval: e.target.value })} /></Field><Field label="超时（秒）"><input type="number" value={value.timeout} onChange={(e) => patch({ timeout: e.target.value })} /></Field><Field label="连续失败"><input type="number" value={value.failureThreshold} onChange={(e) => patch({ failureThreshold: e.target.value })} /></Field><Field label="连续恢复"><input type="number" value={value.recoveryThreshold} onChange={(e) => patch({ recoveryThreshold: e.target.value })} /></Field><Field label="仲裁方式"><select value={value.quorumMode} onChange={(e) => patch({ quorumMode: e.target.value })}><option value="majority">多数探针失败</option><option value="all">全部探针失败</option><option value="count">指定数量失败</option></select></Field><Field label="指定数量"><input type="number" value={value.quorumCount} disabled={value.quorumMode !== 'count'} onChange={(e) => patch({ quorumCount: e.target.value })} /></Field><Multi label="负责探针" items={state.probes} value={value.probeIds} onChange={(probeIds) => patch({ probeIds })} /><Field label="切换策略"><select value={value.policyId} onChange={(e) => patch({ policyId: e.target.value })}><option value="">仅监控，不触发</option>{state.failoverPolicies?.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Toggle checked={value.allowPrivate} onChange={(allowPrivate) => patch({ allowPrivate })}>允许检查私网地址</Toggle><Toggle checked={value.enabled} onChange={(enabled) => patch({ enabled })}>启用检查</Toggle></EditorGrid>;
  if (type === 'asset') return <EditorGrid><Field label="资产名称"><input value={value.name} onChange={(e) => patch({ name: e.target.value })} /></Field><Field label="IP 地址"><input value={value.address} onChange={(e) => patch({ address: e.target.value })} /></Field><Field label="地区"><input value={value.region} onChange={(e) => patch({ region: e.target.value })} /></Field><Field label="运营商"><input value={value.carrier} onChange={(e) => patch({ carrier: e.target.value })} /></Field><Field label="健康状态"><select value={value.health} onChange={(e) => patch({ health: e.target.value })}><option value="unknown">未检测</option><option value="healthy">正常</option><option value="unhealthy">异常</option></select></Field><Field label="标签"><input value={value.labels} onChange={(e) => patch({ labels: e.target.value })} placeholder="逗号分隔" /></Field><Field label="备注" full><textarea value={value.note} onChange={(e) => patch({ note: e.target.value })} /></Field><Toggle checked={value.enabled} onChange={(enabled) => patch({ enabled })}>允许加入备用池</Toggle></EditorGrid>;
  if (type === 'pool') return <EditorGrid><Field label="备用池名称"><input value={value.name} onChange={(e) => patch({ name: e.target.value })} /></Field><Field label="取用方式"><select value={value.allocationMode} onChange={(e) => patch({ allocationMode: e.target.value })}><option value="one">一次取一个</option><option value="count">取指定数量</option><option value="all">取全部可用 IP</option></select></Field><Field label="取用数量"><input type="number" disabled={value.allocationMode !== 'count'} value={value.allocationCount} onChange={(e) => patch({ allocationCount: e.target.value })} /></Field><Field label="选择顺序"><select value={value.selectionMode} onChange={(e) => patch({ selectionMode: e.target.value })}><option value="ordered">固定顺序</option><option value="random">随机</option><option value="weighted">按权重</option></select></Field><Field label="共享策略"><select value={value.sharingMode} onChange={(e) => patch({ sharingMode: e.target.value })}><option value="exclusive">独占</option><option value="target">同目标共享</option><option value="business">同业务共享</option><option value="limited">限量共享</option><option value="unlimited">完全共享</option></select></Field><Field label="最大引用数"><input type="number" disabled={value.sharingMode !== 'limited'} value={value.shareLimit} onChange={(e) => patch({ shareLimit: e.target.value })} /></Field><Field label="租约（分钟）"><input type="number" value={value.leaseMinutes} onChange={(e) => patch({ leaseMinutes: e.target.value })} /></Field><Field label="冷却（分钟）"><input type="number" value={value.cooldownMinutes} onChange={(e) => patch({ cooldownMinutes: e.target.value })} /></Field><Multi label="IP 资产" items={state.ipAssets} value={value.assetIds} onChange={(assetIds) => patch({ assetIds })} secondary={(item) => item.address} /><Field label="备注" full><textarea value={value.note} onChange={(e) => patch({ note: e.target.value })} /></Field></EditorGrid>;
  if (type === 'account') return <EditorGrid><Field label="账号名称"><input value={value.name} onChange={(e) => patch({ name: e.target.value })} /></Field><Field label="服务商"><select value={value.provider} onChange={(e) => patch({ provider: e.target.value, credentials: {} })}>{Object.entries(PROVIDERS).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></Field><Field label="区域"><input value={value.region} onChange={(e) => patch({ region: e.target.value })} /></Field><Field label="Project ID"><input value={value.projectId} onChange={(e) => patch({ projectId: e.target.value })} /></Field>{credentialFields(value, patch)}<Field label="Zone 白名单" full><textarea rows="4" value={value.zoneAllowlist} onChange={(e) => patch({ zoneAllowlist: e.target.value })} placeholder="每行一个允许操作的 Zone" /></Field><Toggle checked={value.enabled} onChange={(enabled) => patch({ enabled })}>启用账号</Toggle></EditorGrid>;
  if (type === 'zone') return <EditorGrid><Field label="Zone"><input value={value.name} onChange={(e) => patch({ name: e.target.value })} placeholder="example.com" /></Field><Field label="服务商账号"><select value={value.accountId} onChange={(e) => patch({ accountId: e.target.value })}><option value="">请选择</option>{state.dnsAccounts?.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="服务商 Zone ID" full><input value={value.providerZoneId} onChange={(e) => patch({ providerZoneId: e.target.value })} /></Field><Toggle checked={value.enabled} onChange={(enabled) => patch({ enabled })}>启用托管</Toggle></EditorGrid>;
  if (type === 'binding') return <BindingEditor value={value} patch={patch} state={state} />;
  if (type === 'bot') return <EditorGrid><Field label="机器人名称"><input value={value.name} onChange={(e) => patch({ name: e.target.value })} /></Field><Field label="Bot Token"><input type="password" value={value.token} onChange={(e) => patch({ token: e.target.value })} placeholder={value.configured ? '留空保持原 Token' : 'BotFather Token'} /></Field><Field label="授权用户 ID" full><textarea rows="4" value={value.userIds} onChange={(e) => patch({ userIds: e.target.value })} placeholder="每行一个用户 ID" /></Field><Field label="授权群组 ID" full><textarea rows="3" value={value.groupIds} onChange={(e) => patch({ groupIds: e.target.value })} placeholder="每行一个群组 ID；留空允许私聊用户" /></Field><Field label="角色分配" full><textarea rows="5" value={value.rolesText} onChange={(e) => patch({ rolesText: e.target.value })} placeholder={'每行：用户ID=角色\n角色：owner / admin / operator / approver / viewer / auditor'} /></Field><Multi label="允许菜单" items={[['overview','总览'],['probes','探针'],['incidents','故障事件'],['pools','备用池'],['dns','解析管理'],['automation','自动化']].map(([id,name]) => ({ id,name }))} value={value.menuScopes} onChange={(menuScopes) => patch({ menuScopes })} /><Toggle checked={value.enabled} onChange={(enabled) => patch({ enabled })}>启用机器人</Toggle></EditorGrid>;
  return <EditorGrid><Field label="策略名称"><input value={value.name} onChange={(e) => patch({ name: e.target.value })} /></Field><Field label="业务标识"><input value={value.businessKey} onChange={(e) => patch({ businessKey: e.target.value })} placeholder="用于同业务共享 IP" /></Field><Multi label="备用池（按顺序兜底）" items={state.ipPools} value={value.poolIds} onChange={(poolIds) => patch({ poolIds })} /><Field label="自动化任务"><select value={value.automationTaskId} onChange={(e) => patch({ automationTaskId: e.target.value })}><option value="">不执行自动化</option>{state.automationTasks?.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="自动化目标"><select value={value.automationHosts} onChange={(e) => patch({ automationHosts: e.target.value })}><option value="allocated">分配出来的备用 IP</option><option value="target">故障目标地址</option></select></Field><Field label="任务超时（秒）"><input type="number" value={value.automationTimeout} onChange={(e) => patch({ automationTimeout: e.target.value })} /></Field><Multi label="解析绑定" items={state.dnsBindings} value={value.dnsBindingIds} onChange={(dnsBindingIds) => patch({ dnsBindingIds })} secondary={(item) => item.domain} /><Field label="执行方式"><select value={value.approvalMode} onChange={(e) => patch({ approvalMode: e.target.value })}><option value="automatic">自动执行</option><option value="telegram">Telegram / Web 确认</option></select></Field><Toggle checked={value.autoRollback} onChange={(autoRollback) => patch({ autoRollback })}>失败时自动回滚</Toggle><Toggle checked={value.enabled} onChange={(enabled) => patch({ enabled })}>启用策略</Toggle></EditorGrid>;
}

function credentialFields(value, patch) {
  const update = (key, next) => patch({ credentials: { ...(value.credentials || {}), [key]: next } });
  if (value.provider === 'cloudflare') return <Field label="API Token" full><input type="password" value={value.credentials?.apiToken || ''} onChange={(e) => update('apiToken', e.target.value)} placeholder={value.configured ? '留空保持原凭证' : ''} /></Field>;
  if (value.provider === 'tencent') return <><Field label="Secret ID"><input type="password" value={value.credentials?.secretId || ''} onChange={(e) => update('secretId', e.target.value)} /></Field><Field label="Secret Key"><input type="password" value={value.credentials?.secretKey || ''} onChange={(e) => update('secretKey', e.target.value)} /></Field></>;
  if (value.provider === 'dnspod') return <><Field label="DNSPod Token ID"><input type="password" value={value.credentials?.tokenId || ''} onChange={(e) => update('tokenId', e.target.value)} /></Field><Field label="DNSPod Token Secret"><input type="password" value={value.credentials?.tokenSecret || ''} onChange={(e) => update('tokenSecret', e.target.value)} /></Field></>;
  if (value.provider === 'godaddy') return <><Field label="API Key"><input type="password" value={value.credentials?.apiKey || ''} onChange={(e) => update('apiKey', e.target.value)} /></Field><Field label="API Secret"><input type="password" value={value.credentials?.apiSecret || ''} onChange={(e) => update('apiSecret', e.target.value)} /></Field></>;
  if (value.provider === 'porkbun') return <><Field label="API Key"><input type="password" value={value.credentials?.apiKey || ''} onChange={(e) => update('apiKey', e.target.value)} /></Field><Field label="Secret API Key"><input type="password" value={value.credentials?.secretApiKey || ''} onChange={(e) => update('secretApiKey', e.target.value)} /></Field></>;
  if (value.provider === 'cloudns') return <><Field label="Auth ID"><input value={value.credentials?.authId || ''} onChange={(e) => update('authId', e.target.value)} /></Field><Field label="Auth Password"><input type="password" value={value.credentials?.authPassword || ''} onChange={(e) => update('authPassword', e.target.value)} /></Field></>;
  if (value.provider === 'callback' || ['aliyun_esa','baidu','namecheap','namesilo','dynadot','dnsla','era','tndns','gcore','edgeone','ns1','rainyun','dynv6','vercel','spaceship'].includes(value.provider)) return <><Field label="HTTPS API 地址" full><input value={value.credentials?.endpoint || ''} onChange={(e) => update('endpoint', e.target.value)} placeholder="https://example.com/ddns" /></Field><Field label="访问令牌 / API Key" full><input type="password" value={value.credentials?.token || ''} onChange={(e) => update('token', e.target.value)} /></Field><Field label="自定义请求头（JSON）" full><textarea rows="3" value={value.credentials?.headers || ''} onChange={(e) => update('headers', e.target.value)} placeholder='{"Authorization":"Bearer ..."}' /></Field><span className="ops-field-hint">该接口将收到 JSON：domain、recordName、recordType、ttl、values、zone。</span></>;
  return <><Field label="Access Key"><input type="password" value={value.credentials?.accessKey || ''} onChange={(e) => update('accessKey', e.target.value)} /></Field><Field label="Secret Key"><input type="password" value={value.credentials?.secretKey || ''} onChange={(e) => update('secretKey', e.target.value)} /></Field></>;
}

function BindingEditor({ value, patch, state }) {
  const sources = Array.isArray(value.ddnsSources) ? value.ddnsSources : [];
  const updateSource = (index, next) => patch({ ddnsSources: sources.map((item, current) => current === index ? { ...item, ...next } : item) });
  return <EditorGrid>
    <Field label="绑定名称"><input value={value.name} onChange={(e) => patch({ name: e.target.value })} /></Field>
    <Field label="服务商账号"><select value={value.accountId} onChange={(e) => patch({ accountId: e.target.value })}><option value="">请选择</option>{state.dnsAccounts?.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field>
    <Field label="DNS Zone"><select value={value.zoneId} onChange={(e) => patch({ zoneId: e.target.value })}><option value="">请选择</option>{state.dnsZones?.filter((item) => !value.accountId || item.accountId === value.accountId).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field>
    <Field label="完整域名"><input value={value.domain} onChange={(e) => patch({ domain: e.target.value })} /></Field>
    <Field label="主机记录"><input value={value.recordName} onChange={(e) => patch({ recordName: e.target.value })} /></Field>
    <Field label="记录类型"><select value={value.recordType} onChange={(e) => patch({ recordType: e.target.value })}><option>A</option><option>AAAA</option></select></Field>
    <Field label="服务商 Record ID（可多个）" full><textarea rows="2" value={(value.providerRecordIds || [value.providerRecordId]).filter(Boolean).join('\n')} onChange={(e) => patch({ providerRecordIds: e.target.value.split(/[,，\n]+/).map((item) => item.trim()).filter(Boolean) })} placeholder="华为云可留空，其他服务商可填多个 Record ID" /></Field>
    <Field label="TTL"><input type="number" value={value.ttl} onChange={(e) => patch({ ttl: e.target.value })} /></Field>
    <Field label="更新方式"><select value={value.updateMode} onChange={(e) => patch({ updateMode: e.target.value })}><option value="append">追加 IP</option><option value="managed_replace">覆盖托管值</option><option value="replace">完全替换</option></select></Field>
    <div className="ops-multi"><strong>主/备用解析来源</strong><div className="ops-source-list">{sources.map((source, index) => <div className="ops-source-row" key={source.id || index}><input value={source.name || ''} placeholder="来源名称" onChange={(e) => updateSource(index, { name: e.target.value })} /><input value={source.domain || ''} placeholder="主域名" onChange={(e) => updateSource(index, { domain: e.target.value })} /><input value={source.backupDomain || ''} placeholder="备用域名（可选）" onChange={(e) => updateSource(index, { backupDomain: e.target.value })} /><button className="icon-button danger" title="删除来源" onClick={() => patch({ ddnsSources: sources.filter((_, current) => current !== index) })}>×</button></div>)}<button className="ghost" onClick={() => patch({ ddnsSources: [...sources, { id: crypto.randomUUID(), name: '', domain: '', backupDomain: '' }] })}>添加来源</button></div></div>
    <Field label="固定备用 IP（每行一个）" full><textarea rows="3" value={(value.backupIps || []).join?.('\n') || value.backupIps || ''} onChange={(e) => patch({ backupIps: e.target.value.split(/[,，\n]+/).map((item) => item.trim()).filter(Boolean) })} /></Field>
    <Field label="活动地址上限"><input type="number" min="1" max="50" value={value.maxActiveIps} onChange={(e) => patch({ maxActiveIps: e.target.value })} /></Field>
    <Field label="健康检测间隔（秒）"><input type="number" value={value.healthInterval} onChange={(e) => patch({ healthInterval: e.target.value })} /></Field>
    <Field label="检测并发"><input type="number" value={value.maxParallel} onChange={(e) => patch({ maxParallel: e.target.value })} /></Field>
    <Toggle checked={value.pruneStale} onChange={(pruneStale) => patch({ pruneStale })}>清理失效/过期地址</Toggle><Toggle checked={value.healthEnabled} onChange={(healthEnabled) => patch({ healthEnabled })}>启用健康检测</Toggle><Toggle checked={value.enabled} onChange={(enabled) => patch({ enabled })}>启用解析绑定</Toggle>
  </EditorGrid>;
}

function EditorGrid({ children }) { return <div className="ops-editor-grid">{children}</div>; }
function Field({ label, children, full }) { return <label className={full ? 'ops-field full' : 'ops-field'}><span>{label}</span>{children}</label>; }
function Toggle({ checked, onChange, children }) { return <label className="ops-toggle"><input type="checkbox" checked={Boolean(checked)} onChange={(e) => onChange(e.target.checked)} /><span>{children}</span></label>; }
function Multi({ label, items = [], value = [], onChange, secondary }) { return <div className="ops-multi"><strong>{label}</strong><div>{items.map((item) => <label key={item.id}><input type="checkbox" checked={value.includes(item.id)} onChange={() => onChange(value.includes(item.id) ? value.filter((id) => id !== item.id) : [...value, item.id])} /><span>{item.name || item.address}<em>{secondary?.(item)}</em></span></label>)}</div></div>; }

function resourceFor(type) { return ({ probe: 'probes', target: 'probe-targets', asset: 'ip-assets', pool: 'ip-pools', account: 'dns-accounts', zone: 'dns-zones', binding: 'dns-bindings', policy: 'failover-policies', bot: 'telegram-bots' })[type]; }
function typeLabel(type) { return ({ probe: '探针', target: '检查目标', asset: 'IP 资产', pool: '备用池', account: 'DNS 账号', zone: 'DNS Zone', binding: '解析绑定', policy: '切换策略', bot: 'Telegram 机器人' })[type]; }
function normalizeDraft(type, value) { const draft = { ...structuredClone(EMPTY[type]), ...structuredClone(value) }; if (type === 'asset') draft.labels = (value.labels || []).join(', '); if (type === 'account') { draft.zoneAllowlist = (value.zoneAllowlist || []).join('\n'); draft.credentials = {}; } if (type === 'bot') { draft.token = ''; draft.userIds = (value.userIds || []).join('\n'); draft.groupIds = (value.groupIds || []).join('\n'); draft.rolesText = Object.entries(value.roles || {}).map(([id, role]) => `${id}=${role}`).join('\n'); } return draft; }
function serializeDraft(type, value) { const draft = structuredClone(value); if (type === 'asset') draft.labels = String(draft.labels || '').split(/[,，\n]+/).map((item) => item.trim()).filter(Boolean); if (type === 'account') draft.zoneAllowlist = String(draft.zoneAllowlist || '').split(/[,，\n]+/).map((item) => item.trim()).filter(Boolean); if (type === 'bot') { draft.userIds = String(draft.userIds || '').split(/[,，\n]+/).map((item) => item.trim()).filter(Boolean); draft.groupIds = String(draft.groupIds || '').split(/[,，\n]+/).map((item) => item.trim()).filter(Boolean); draft.roles = Object.fromEntries(String(draft.rolesText || '').split(/\n+/).map((line) => line.split('=').map((part) => part.trim())).filter(([id, role]) => id && role)); } return draft; }
function countFor(section, state) { return ({ nodes: state.probes, targets: state.probeTargets, policies: state.failoverPolicies, incidents: state.incidents, bots: state.telegramBots, assets: state.ipAssets, pools: state.ipPools, leases: state.ipLeases, accounts: state.dnsAccounts, zones: state.dnsZones, bindings: state.dnsBindings, changes: state.dnsChanges })[section]?.length || 0; }
function summary(tab, state) { if (tab === 'probes') return `${state.probes?.filter((item) => item.status === 'online').length || 0} 个在线探针 · ${state.incidents?.filter((item) => !['succeeded', 'rolled_back'].includes(item.status)).length || 0} 个活动事件`; if (tab === 'pools') return `${state.ipAssets?.length || 0} 个 IP · ${state.ipLeases?.filter((item) => ['active', 'locked'].includes(item.status)).length || 0} 个活动租约`; return `${state.dnsAccounts?.length || 0} 个账号 · ${state.dnsBindings?.length || 0} 条解析绑定`; }
function allocationLabel(item) { return item.allocationMode === 'all' ? '全部取用' : item.allocationMode === 'count' ? `取 ${item.allocationCount} 个` : '一次取一个'; }
function sharingLabel(mode) { return ({ exclusive: '独占', target: '同目标共享', business: '同业务共享', limited: '限量共享', unlimited: '完全共享' })[mode] || mode; }
function updateModeLabel(mode) { return ({ append: '追加 IP', managed_replace: '覆盖托管值', replace: '完全替换' })[mode] || mode; }
function formatTime(value) { if (!value) return '-'; return new Date(value).toLocaleString('zh-CN', { hour12: false }); }
